#!/usr/bin/env sh
nvim="$HOME/.config/nvim"
repos="https://github.com/jimzhan/nvim"
config=$HOME/.config

info() {
    printf "\e[34m[⊙]\e[0m ${1}\n"
}

error() {
    printf "\e[31m[✘]\e[0m ${1}\n"
}

success() {
    printf "\e[32m[✔]\e[0m ${1}\n"
}


# ------------------------------
# ensure there is a global config folder.
# ------------------------------
if [ ! -d $config ]; then
    mkdir -p $config
fi


# ------------------------------
# backup/unlink existing nvim if any.
# ------------------------------
if [ -L $config/nvim ]; then
    unlink $config/nvim
    info "[neovim] existing config unlinked"
elif [ -d $config/nvim ]; then
    mv $config/nvim $config/nvim.bak
    info "nvim => nvim.bak"
fi


# clone/update from remote repos
# ------------------------------
if [ ! -d $nvim ]; then
    info "Setting up NeoVim...\n"
    git clone $repos $nvim
    mkdir $nvim/tmp
    success "NeoVim is ready to launch now"
fi
